---
resources:
  - name: 'concourse-java_11_github'
    old_name: 'concourse-java:11 @github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-java/11/Dockerfile
  - name: 'concourse-java_11_dockerhub'
    old_name: 'concourse-java:11 @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-java" ))
      tag: "11"

jobs:
  - name: 'build-concourse-java_11'
    old_name: 'build-concourse-java:11'
    public: true
    plan:
      - { get: git, resource: 'concourse-java_11_github',    trigger: true }
      - { get: img, resource: 'concourse_latest_dockerhub', trigger: true, passed: ['build-concourse_latest'], params: {skip_download: true} }
      - put: 'concourse-java_11_dockerhub'
        params:
          build: git/concourse-java/11
          tag_as_latest: true
