---
resources:
  - name: 'concourse-ruby_3_0_github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-ruby/3.0/Dockerfile
  - name: 'concourse-ruby_3_0_dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-ruby" ))
      tag: "3.0"

jobs:
  - name: 'build-concourse-ruby_3_0'
    public: true
    plan:
      - { get: git, resource: 'concourse-ruby_3_0_github',    trigger: true }
      - { get: img, resource: 'concourse_latest_dockerhub', trigger: true, passed: ['build-concourse_latest'], params: {skip_download: true} }
      - put: 'concourse-ruby_3_0_dockerhub'
        params:
          build: git/concourse-ruby/3.0
          tag_as_latest: true
