---
resources:
  - name: concourse_ubuntu-jammy-github
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse/ubuntu-jammy/Dockerfile
        - concourse/ubuntu-jammy/scripts/*

  - name: ubuntu-jammy-version
    .: (( inject meta.resources.dockerhub ))
    type: registry-image
    source:
      email: ((prune))
      repository: ubuntu
      variant: jammy

  - name: concourse_ubuntu-jammy-image
    .: (( inject meta.resources.local-registry ))
    source:
      repository: (( concat meta.image-registry.account "/concourse" ))
      tag: ubuntu-jammy

  - name: concourse_latest-image
    .: (( inject meta.resources.local-registry ))
    source:
      repository: (( concat meta.image-registry.account "/concourse" ))
      tag: latest


  - name: concourse_ubuntu-jammy-dockerhub
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse" ))
      tag: ubuntu-jammy

  - name: concourse_latest-dockerhub
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse" ))
      tag: latest

jobs:
  - name: build-concourse_ubuntu-jammy
    public: true
    plan:
      - get: git
        resource: 'concourse_ubuntu-jammy-github'
        trigger:  true
      - get: ubuntu-jammy-version
        resource: ubuntu-jammy-version
        trigger: true
        params:
          skip_download: true
      - put: concourse_ubuntu-jammy-image
        get_params: {save: true}
        params:
          build: git/concourse/ubuntu-jammy

      - put: concourse_latest-image
        params:
          load: concourse_ubuntu-jammy-image

      - put: concourse_ubuntu-jammy-dockerhub
        params:
          load: concourse_ubuntu-jammy-image

      - put: concourse_latest-dockerhub
        params:
          load: concourse_ubuntu-jammy-image
