---
resources:
  - name: 'concourse-ruby_3_1_github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-ruby/3.1/Dockerfile
  - name: 'concourse-ruby_3_1_dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-ruby" ))
      tag: "3.1"

jobs:
  - name: 'build-concourse-ruby_3_1'
    public: true
    plan:
      - { get: git, resource: 'concourse-ruby_3_1_github',    trigger: true }
      - { get: img, resource: 'concourse_latest_dockerhub', trigger: true, passed: ['build-concourse_latest'], params: {skip_download: true} }
      - put: 'concourse-ruby_3_1_dockerhub'
        params:
          build: git/concourse-ruby/3.1
          tag_as_latest: true
