---
resources:
  - name: 'concourse-nodejs_12_github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-nodejs/12/Dockerfile
  - name: 'concourse-nodejs_12_dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-nodejs" ))
      tag: "12"

jobs:
  - name: 'build-concourse-nodejs_12'
    public: true
    plan:
      - { get: git, resource: 'concourse-nodejs_12_github',    trigger: true }
      - { get: img, resource: 'concourse_latest_dockerhub', trigger: true, passed: ['build-concourse_latest'], params: {skip_download: true} }
      - put: 'concourse-nodejs_12_dockerhub'
        params:
          build: git/concourse-nodejs/12
          tag_as_latest: true
