---
groups:
  - name: all
    jobs:
    - "*"
  - name: concourse
    jobs:
    - "build-concourse_*"
    - "publish-concourse_*"

notgroups:
  - name: concourse-go
    jobs:
    - "build-concourse-go_*"
  - name: concourse-java
    jobs:
    - "build-concourse-java_*"
  - name: concourse-ruby
    jobs:
    - "build-concourse-ruby_*"
  - name: concourse-nodejs
    jobs:
    - "build-concourse-nodejs_*"
  - name: concourse-kubernetes
    jobs:
    - "build-concourse-kubernetes_*"
  - name: gcp-cloudshell
    jobs:
    - "bump-upstream-cloudshell_*"
