---
meta:
  docker:
    account:  ((dockerhub.username))
    email:    ((dockerhub.email))
    username: ((dockerhub.username))
    password: ((dockerhub.password))

  github:
    key:          ((github.private_key))
    access_token: ((github.access-token))

  git:
    email: genesis-ci@rubidiumstudios.com
    name:  Genesis CI Bot

  resources:
    dockerfiles:
      type: git
      source:
        uri: git@github.com:genesis-community/concourse-dockerfiles
        branch: main
        private_key: (( grab meta.github.key ))

    dockerhub:
      type: docker-image
      source:
        email:    (( grab meta.docker.email ))
        username: (( grab meta.docker.username ))
        password: (( grab meta.docker.password ))

    github-release:
      type: github-release
      source:
        access_token: (( grab meta.github.access_token ))

    git:
      type: git
      source:
        private_key: (( grab meta.github.key ))

groups:
  - name: all
    jobs:
    - "*"
  - name: concourse
    jobs:
    - "build-concourse_*"

notgroups:
  - name: concourse-go
    jobs:
    - "build-concourse-go_*"
  - name: concourse-java
    jobs:
    - "build-concourse-java_*"
  - name: concourse-ruby
    jobs:
    - "build-concourse-ruby_*"
  - name: concourse-nodejs
    jobs:
    - "build-concourse-nodejs_*"
  - name: concourse-kubernetes
    jobs:
    - "build-concourse-kubernetes_*"
  - name: gcp-cloudshell
    jobs:
    - "bump-upstream-cloudshell_*"
