---
meta:
  dockerhub:
    account:  starkandwayne
    email:    ((dockerhub-email))
    username: ((dockerhub-username))
    password: ((dockerhub-password))

  gcr: # Google Container Registry
    account: gcr.io/starkandwayne-registry
    username: _json_key
    password: ((gcr-service-account-key))

  github:
    key: ((github.private-key))
    access_token: ((github.access-token))

  git:
    email: ci@starkandwayne.com
    name:  CI Bot

  resources:
    dockerfiles:
      type: git
      source:
        uri: git@github.com:starkandwayne/dockerfiles
        branch: master
        private_key: (( grab meta.github.key ))

    gcr:
      type: docker-image
      source:
        username: (( grab meta.gcr.username ))
        password: (( grab meta.gcr.password ))

    dockerhub:
      type: docker-image
      source:
        email:    (( grab meta.dockerhub.email ))
        username: (( grab meta.dockerhub.username ))
        password: (( grab meta.dockerhub.password ))

    github-release:
      type: github-release
      source:
        access_token: (( grab meta.github.access_token ))

    git:
      type: git
      source:
        private_key: (( grab meta.github.key ))

groups:
  - name: all
    jobs:
    - "*"
  - name: concourse
    jobs:
    - "build-concourse_*"
  - name: concourse-go
    jobs:
    - "build-concourse-go_*"
  - name: concourse-java
    jobs:
    - "build-concourse-java_*"
  - name: concourse-ruby
    jobs:
    - "build-concourse-ruby_*"
  - name: concourse-nodejs
    jobs:
    - "build-concourse-nodejs_*"
  - name: concourse-kubernetes
    jobs:
    - "build-concourse-kubernetes_*"
  - name: gcp-cloudshell
    jobs:
    - "bump-upstream-cloudshell_*"
