---
meta:
  dockerhub:
    account:  starkandwayne
    email:    (( vault "secret/pipelines/dockerfiles/dockerhub:email" ))
    username: (( vault "secret/pipelines/dockerfiles/dockerhub:username" ))
    password: (( vault "secret/pipelines/dockerfiles/dockerhub:password" ))

  github:
    key: (( vault "secret/pipelines/dockerfiles/github:key" ))

  resources:
    dockerfiles:
      type: git
      source:
        uri: git@github.com:starkandwayne/dockerfiles
        branch: master
        private_key: (( grab meta.github.key ))

    dockerhub:
      type: docker-image
      source:
        email:    (( grab meta.dockerhub.email ))
        username: (( grab meta.dockerhub.username ))
        password: (( grab meta.dockerhub.password ))

groups:
  - name: '*'
    jobs: (( grab groups.concourse.jobs groups.concourse-go.jobs groups.concourse-java.jobs groups.concourse-ruby.jobs groups.concourse-nodejs.jobs ))
  - name: concourse
  - name: concourse-go
  - name: concourse-java
  - name: concourse-ruby
  - name: concourse-nodejs
  - name: concourse-oldbosh
