---
resources:
  - name: 'concourse-go_1.14_github'
    old_name: 'concourse-go:1.14 @github'
    .: (( inject meta.resources.dockerfiles ))
    source:
      paths:
        - concourse-go/1.14/Dockerfile
  - name: 'concourse-go_1.14_dockerhub'
    old_name: 'concourse-go:1.14 @dockerhub'
    .: (( inject meta.resources.dockerhub ))
    source:
      repository: (( concat meta.dockerhub.account "/concourse-go" ))
      tag: "1.14"

jobs:
  - name: 'build-concourse-go_1.14'
    old_name: 'build-concourse-go:1.14'
    public: true
    plan:
      - { get: git, resource: 'concourse-go_1.14_github',   trigger: true }
      - { get: img, resource: 'concourse_latest_dockerhub', trigger: true, passed: ['build-concourse_latest'], params: {skip_download: true} }
      - put: 'concourse-go_1.14_dockerhub'
        params:
          build: git/concourse-go/1.14
          tag_as_latest: true
